### What is NumPy?

NumPy stands for Numerical Python. It's a library used to work with arrays (Especially multidimensional arrays), and provides tools for:
- Fast mathematical operations on arrays
- Linear algebra
- Random number generation
- Integration with C/C++/Fortran code
---
### Why NumPy in Data Science?
- Data in real world = arrays (tables, images, time series)
- NumPy arrays are faster and more memory-efficient than Python lists
- Used heavily for data preprocessing, statistics, and model input
---
### Getting Started

In [1]:
pip install numpy

In [2]:
import numpy as np

---
#### 1. Creating Arrays

In [19]:
a = np.array([1, 2, 3])     # 1D array
b = np.array([[1, 2],[3, 4]])       # 2D array
print(a)
print(b)

# Common ways to create arrays:

print("2x3 array of 0s\n", np.zeros((2,3)))     # 2x3 array of 0s
print("1D Array of 1s\n", np.ones((3,)))        # 1D array of 1s
print("2x2 array filled with 7\n", np.full((2,2), 7))       # 2x2 array filled with 7
print("3x3 identity Matrix\n", np.eye(3))       # 3x3 identity matrix
print("[0,2,4,6,8]\n", np.arange(0, 10, 2))        # [0, 2, 4, 6, 8]
print("5 evenly spaced numbers between 0 and 10\n", np.linspace(0, 10, 5))       # 5 evenly spaced numbers between 0 and 1

[1 2 3]
[[1 2]
 [3 4]]
2x3 array of 0s
 [[0. 0. 0.]
 [0. 0. 0.]]
1D Array of 1s
 [1. 1. 1.]
2x2 array filled with 7
 [[7 7]
 [7 7]]
3x3 identity Matrix
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0,2,4,6,8]
 [0 2 4 6 8]
5 evenly spaced numbers between 0 and 10
 [ 0.   2.5  5.   7.5 10. ]


---
#### 2. Array Properties

In [20]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)


(2, 3)
2
6
int64


---
#### 3. Indexing & Slicing

In [ ]:
print(arr)
print(arr[1,1]) # Print element at row index 1 and column index 1
print(arr[1])   # Print row index 1
print(arr[0])   # Print row index 0
print(arr[:, 1])# Print all elements from all rows, with column index 1 [2, 5]
print(arr[:, 2])# Print all elements from all rows, with column index 2 [3, 6]
print(arr[0:2, 0:2]) # Sub array

[[1 2 3]
 [4 5 6]]
5
[4 5 6]
[1 2 3]
[2 5]
[3 6]
[[1 2]
 [4 5]]


---
#### 4. Array Operations