### What is NumPy?

NumPy stands for Numerical Python. It's a library used to work with arrays (Especially multidimensional arrays), and provides tools for:
- Fast mathematical operations on arrays
- Linear algebra
- Random number generation
- Integration with C/C++/Fortran code
---
### Why NumPy in Data Science?
- Data in real world = arrays (tables, images, time series)
- NumPy arrays are faster and more memory-efficient than Python lists
- Used heavily for data preprocessing, statistics, and model input
---
### Getting Started

In [1]:
pip install numpy

In [2]:
import numpy as np

---
#### 1. Creating Arrays

In [19]:
a = np.array([1, 2, 3])     # 1D array
b = np.array([[1, 2],[3, 4]])       # 2D array
print(a)
print(b)

# Common ways to create arrays:

print("2x3 array of 0s\n", np.zeros((2,3)))     # 2x3 array of 0s
print("1D Array of 1s\n", np.ones((3,)))        # 1D array of 1s
print("2x2 array filled with 7\n", np.full((2,2), 7))       # 2x2 array filled with 7
print("3x3 identity Matrix\n", np.eye(3))       # 3x3 identity matrix
print("[0,2,4,6,8]\n", np.arange(0, 10, 2))        # [0, 2, 4, 6, 8]
print("5 evenly spaced numbers between 0 and 10\n", np.linspace(0, 10, 5))       # 5 evenly spaced numbers between 0 and 1

[1 2 3]
[[1 2]
 [3 4]]
2x3 array of 0s
 [[0. 0. 0.]
 [0. 0. 0.]]
1D Array of 1s
 [1. 1. 1.]
2x2 array filled with 7
 [[7 7]
 [7 7]]
3x3 identity Matrix
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0,2,4,6,8]
 [0 2 4 6 8]
5 evenly spaced numbers between 0 and 10
 [ 0.   2.5  5.   7.5 10. ]


---
#### 2. Array Properties

In [20]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)


(2, 3)
2
6
int64


---
#### 3. Indexing & Slicing

In [ ]:
print(arr)
print(arr[1,1]) # Print element at row index 1 and column index 1
print(arr[1])   # Print row index 1
print(arr[0])   # Print row index 0
print(arr[:, 1])# Print all elements from all rows, with column index 1 [2, 5]
print(arr[:, 2])# Print all elements from all rows, with column index 2 [3, 6]
print(arr[0:2, 0:2]) # Sub array

[[1 2 3]
 [4 5 6]]
5
[4 5 6]
[1 2 3]
[2 5]
[3 6]
[[1 2]
 [4 5]]


---
#### 4. Array Operations

In [34]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Addition of a and b ", a + b )
print("Multiplication of a and b ", a * b)
print("Square of array a ", a ** 2)
print("Cube of array b ", b ** 3)

Addition of a and b  [5 7 9]
Multiplication of a and b  [ 4 10 18]
Square of array a  [1 4 9]
Cube of array b  [ 64 125 216]


***
#### 5. Boolean Masking & Filtering

In [37]:
a = np.array([1, 2, 3, 4, 5])

mask = a > 2
print(mask)
print(a[a>3])
print(a[a % 2 != 0])

[False False  True  True  True]
[4 5]
[1 3 5]


---
#### 6. Reshaping Arrays

In [44]:
a = np.arange(6)
print(a)
a = a.reshape(3,2)
print(a)

a = np.array([[1, 2, 3],[4, 5, 6]])
print(a)
a = a.flatten() 
print(a)

[0 1 2 3 4 5]
[[0 1]
 [2 3]
 [4 5]]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


---
#### 7. Matrix Operations

In [49]:
A = np.array([[1, 2],[3, 4]])
B = np.array([[5, 6],[7, 8]])

print(A)
print(B)

print(A @ B)
print(np.dot(A, B))
print(np.transpose(A))
np.linalg.inv(A)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[1 3]
 [2 4]]


array([[-2. ,  1. ],
       [ 1.5, -0.5]])

---
#### 8. Random Number (useful in ML)

In [60]:
randNo = np.random.seed(0)
print(randNo)
print(np.random.rand(2,3))
print(np.random.randn(3))
print(np.random.randint(0, 10, 5))

None
[[0.5488135  0.71518937 0.60276338]
 [0.54488318 0.4236548  0.64589411]]
[ 0.95008842 -0.15135721 -0.10321885]
[6 7 7 8 1]


---
#### 9. Useful NumPy Functions in Data Science

In [75]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr)
print(np.unique(arr))
print(arr[np.argmax(arr)])
print(np.argsort(arr))
print(np.cumsum(arr))

print("-------------------")

arr1 = np.array([10,9,8,7,6,5,4,3,2,1])
print(np.argsort(arr1))

arr2d = np.array([[1,2,3,4,5],[10,9,8,7,6]])
print(arr2d)
print(np.argsort(arr2d))
print(np.where(arr2d > 2))

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
10
[0 1 2 3 4 5 6 7 8 9]
[ 1  3  6 10 15 21 28 36 45 55]
-------------------
[9 8 7 6 5 4 3 2 1 0]
[[ 1  2  3  4  5]
 [10  9  8  7  6]]
[[0 1 2 3 4]
 [4 3 2 1 0]]
(array([0, 0, 0, 1, 1, 1, 1, 1]), array([2, 3, 4, 0, 1, 2, 3, 4]))
